'use client';

import { Sparkles } from 'lucide-react';

interface AIContentBadgeProps {
  visible?: boolean;
  className?: string;
  size?: 'sm' | 'md';
}

/**
 * Subtle "AI-generated" indicator badge for dynamically sourced content.
 * Shows only when content has isAI: true flag from admin curation pipeline.
 * Designed for educational transparency — not intrusive.
 */
export function AIContentBadge({ visible = false, className = '', size = 'sm' }: AIContentBadgeProps) {
  if (!visible) return null;

  const sizeClasses = size === 'sm'
    ? 'px-1.5 py-0.5 text-[9px] gap-0.5'
    : 'px-2 py-1 text-[10px] gap-1';
  const iconSize = size === 'sm' ? 'w-2.5 h-2.5' : 'w-3 h-3';

  return (
    <span
      className={`
        inline-flex items-center ${sizeClasses} rounded-full
        bg-spark-purple/10 text-spark-purple/60 border border-spark-purple/15
        font-data uppercase tracking-wider select-none
        ${className}
      `}
      title="This content was generated by AI and reviewed by an admin"
      aria-label="AI-generated content"
    >
      <Sparkles className={iconSize} />
      AI
    </span>
  );
}
