// ════════════════════════════════════════════════════════════════════════
// CONTEXT ARCHITECT v4 — Lab 8 Flagship (Redesigned)
// ════════════════════════════════════════════════════════════════════════
// Design optimal context windows for AI systems. Quiz-based:
// prompt engineering, attention mechanisms, context sizing, RAG patterns.
// 10 levels from basic context to advanced retrieval architecture.

'use client';
import { useCallback } from 'react';
import { GameShell } from '@/components/game/GameShell';
import { useGameActions } from '@/stores/gameStore';
import GameLevelSystem, { type LevelResult } from '@/components/games/shared/GameLevelSystem';
import QuizLevelRenderer, { type QuizQuestion, type QuizBonusRound } from '@/components/games/shared/QuizLevelRenderer';

// Bonus drag-to-order round: how a well-built prompt is layered.
const BONUS_ROUND: QuizBonusRound = {
  title: 'Build a strong prompt',
  prompt: 'Drag the parts of a prompt into the order that gives the AI the clearest context.',
  items: [
    { id: 'role', label: 'Set the role (who the AI should act as)', correctPosition: 0, currentPosition: 0, color: '#8F96FA' },
    { id: 'context', label: 'Give the background context', correctPosition: 1, currentPosition: 1, color: '#3B82F6' },
    { id: 'task', label: 'State the task / question', correctPosition: 2, currentPosition: 2, color: '#F59E0B' },
    { id: 'format', label: 'Describe the answer format', correctPosition: 3, currentPosition: 3, color: '#10B981' },
  ],
};

const LEVELS = [
  { id: 1, name: 'Context Basics', description: 'What lives in the context window?', emoji: '🪟', difficulty: 'easy' as const, starThresholds: [60,80,95], xpReward: 50 },
  { id: 2, name: 'Token Budget', description: 'Manage your token allowance!', emoji: '💰', difficulty: 'easy' as const, starThresholds: [60,80,95], xpReward: 60 },
  { id: 3, name: 'Prompt Parts', description: 'Deconstruct a prompt!', emoji: '🧩', difficulty: 'easy' as const, starThresholds: [60,80,95], xpReward: 70 },
  { id: 4, name: 'Attention', description: 'How attention focuses on what matters!', emoji: '👁️', difficulty: 'medium' as const, starThresholds: [60,80,90], xpReward: 80 },
  { id: 5, name: 'Context Tricks', description: 'Techniques to fit more in!', emoji: '🎭', difficulty: 'medium' as const, starThresholds: [60,80,90], xpReward: 90 },
  { id: 6, name: 'RAG Intro', description: 'Retrieval-Augmented Generation!', emoji: '🔍', difficulty: 'medium' as const, starThresholds: [50,75,90], xpReward: 100 },
  { id: 7, name: 'System Prompts', description: 'Craft the perfect instruction!', emoji: '⚙️', difficulty: 'hard' as const, starThresholds: [50,75,85], xpReward: 120 },
  { id: 8, name: 'Multi-turn', description: 'Manage conversation history!', emoji: '💬', difficulty: 'hard' as const, starThresholds: [50,75,85], xpReward: 130 },
  { id: 9, name: 'Long Context', description: 'Handle huge documents!', emoji: '📚', difficulty: 'expert' as const, starThresholds: [50,70,85], xpReward: 150 },
  { id: 10, name: 'Context Master', description: 'The ultimate context challenge!', emoji: '👑', difficulty: 'expert' as const, starThresholds: [50,70,85], xpReward: 200, isBonus: true },
];

function getQuestions(levelId: number): QuizQuestion[] {
  const q: Record<number, QuizQuestion[]> = {
    1: [
      { question: "What lives in a language model's context window?", options: ["The model's long-term memory","The current conversation and instructions","The entire internet","Only the last word typed"], correctIndex: 1, explanation: "The context window holds the current conversation, system instructions, and any retrieved information — everything the model can 'see' right now.", band: 'A' },
      { question: "What happens when the context window gets too full?", options: ["The model gets smarter","The model forgets older information","The model shuts down","Nothing happens"], correctIndex: 1, explanation: "When context exceeds the window limit, older tokens are pushed out or summarized. The model literally can't see them anymore.", band: 'A' },
      { question: "Which takes up more tokens in context?", options: ["A single letter","A short word like 'cat'","A long paragraph","They're all the same"], correctIndex: 2, explanation: "More text = more tokens. A long paragraph consumes significantly more of the context budget than a single word.", band: 'A' },
      { question: "Can a model access information NOT in its context window?", options: ["Yes — it knows everything","No — it can only see what's in context","Sometimes — it guesses","Only if connected to the internet"], correctIndex: 1, explanation: "A model cannot access information outside its context window. Its knowledge comes only from what is placed in context during that specific query.", band: 'B' },
      { question: "What is a 'system prompt'?", options: ["A prompt about computer systems","Instructions that define the AI's behavior","A prompt that uses code","A prompt from the operating system"], correctIndex: 1, explanation: "The system prompt sets the AI's role, rules, and constraints. It sits at the beginning of the context and guides all responses.", band: 'A' },
      { question: "If a model has a 4,000 token limit and your prompt is 5,000 tokens, what happens?", options: ["It processes all 5,000 tokens","It ignores the extra 1,000 tokens","It crashes","It automatically compresses them"], correctIndex: 1, explanation: "The model can only process up to its token limit. Extra tokens beyond the limit are typically truncated (cut off) or rejected.", band: 'B' },
      { question: "Which is the MOST efficient way to use context?", options: ["Write extremely detailed prompts","Include only relevant information","Copy-paste entire books","Use as many words as possible"], correctIndex: 1, explanation: "Efficient context use means including only information relevant to the task. Every unnecessary word consumes tokens that could be used for the response.", band: 'A' },
      { question: "What does 'context' mean in AI?", options: ["The model's training data","Everything the model can currently see","The computer's background","The model's source code"], correctIndex: 1, explanation: "Context is everything currently visible to the model in a conversation — your question, previous messages, system instructions, and any provided documents.", band: 'A' },
    ],
    2: [
      { question: "How many tokens does a typical English word use?", options: ["Always 1 token","About 0.75 words per token","Exactly 2 tokens","It varies by word length"], correctIndex: 1, explanation: "On average, one token represents about 0.75 English words. 'Token' is not the same as 'word' — it's a subword unit the model processes.", band: 'B' },
      { question: "If you have a 2,000 token budget, what's the smartest approach?", options: ["Use all 2,000 for the prompt","Reserve some tokens for the AI's answer","Spend them all on fancy formatting","Ignore the budget entirely"], correctIndex: 1, explanation: "Smart budget management reserves tokens for both the prompt AND the response. The model needs budget space to generate its answer.", band: 'A' },
      { question: "What is 'token pricing' in AI APIs?", options: ["Buying physical tokens","Charging based on tokens used","Pricing per word","Free for everyone"], correctIndex: 1, explanation: "AI APIs typically charge per token — both input tokens (your prompt) and output tokens (the AI's response). Efficient prompts save money.", band: 'B' },
      { question: "Which prompt technique saves tokens?", options: ["Adding extra adjectives","Being concise and specific","Repeating the question","Using very long examples"], correctIndex: 1, explanation: "Concise, specific prompts use fewer tokens while being more effective. Every word should earn its place in the context.", band: 'A' },
      { question: "What happens if you give an AI a 10,000-word document when its limit is 4,000 tokens?", options: ["It reads the whole thing","It only processes the first ~3,000 words","It gets smarter","It automatically summarizes"], correctIndex: 1, explanation: "The model can only process tokens within its limit. A 10,000-word document far exceeds 4,000 tokens and will be truncated.", band: 'B' },
      { question: "Are emojis more or less token-efficient than words?", options: ["Always more efficient","Sometimes more, sometimes less","Always less efficient","Emojis are free"], correctIndex: 1, explanation: "Emojis vary — some use 1-3 tokens. They can be efficient for conveying tone but aren't universally better than words.", band: 'B' },
      { question: "What is 'context compression'?", options: ["Shrinking the model size","Summarizing long context to fit","Removing the context window","Compressing images"], correctIndex: 1, explanation: "Context compression techniques summarize or selectively include portions of long documents to fit within the token limit while preserving key information.", band: 'B' },
      { question: "Which takes MORE tokens: 'Hello' or 'supercalifragilisticexpialidocious'?", options: ["Hello","supercalifragilisticexpialidocious","They're the same","It depends on the model"], correctIndex: 1, explanation: "Longer, more unusual words typically require more tokens. Simple common words like 'Hello' often fit in just 1 token.", band: 'A' },
    ],
    3: [
      { question: "What are the three main parts of a well-structured prompt?", options: ["Introduction, Body, Conclusion","Instruction, Context, Output Format","Beginning, Middle, End","Question, Answer, Explanation"], correctIndex: 1, explanation: "A well-structured prompt has: (1) clear instruction (what to do), (2) relevant context (background info), and (3) output format (how to respond).", band: 'B' },
      { question: "What does 'zero-shot' prompting mean?", options: ["Giving zero instructions","Asking without examples","Prompting with no context","A failed prompt"], correctIndex: 1, explanation: "Zero-shot means asking the AI to do something without providing examples. It relies entirely on the model's pre-trained knowledge.", band: 'B' },
      { question: "What does 'few-shot' prompting mean?", options: ["Using very few tokens","Providing a few examples in the prompt","Prompting only once","A cheap prompt"], correctIndex: 1, explanation: "Few-shot prompting includes a few examples of desired input-output pairs in the context, helping the model understand the pattern.", band: 'B' },
      { question: "Why are examples in few-shot prompts placed BEFORE the actual question?", options: ["It's just a convention","The model processes context left-to-right","Examples don't matter","It saves tokens"], correctIndex: 1, explanation: "Language models process context left-to-right. Examples placed before the question act as demonstrations the model can reference when generating its response.", band: 'C' },
      { question: "What is a 'chain-of-thought' prompt?", options: ["A very long prompt","A prompt that asks the model to show its reasoning step-by-step","A prompt about chains","A prompt with multiple questions"], correctIndex: 1, explanation: "Chain-of-thought prompting asks the model to explain its reasoning step by step. This often improves accuracy on complex problems.", band: 'C' },
      { question: "What is 'role prompting'?", options: ["Casting actors","Assigning a persona to the AI","Prompting about jobs","Role-playing games"], correctIndex: 1, explanation: "Role prompting assigns the AI a specific persona (e.g., 'You are an expert marine biologist'). This frames responses through that expertise lens.", band: 'B' },
      { question: "What is a 'delimiter' in prompt engineering?", options: ["A type of punctuation","Special markers that separate sections","A programming term","A type of prompt"], correctIndex: 1, explanation: "Delimiters like triple quotes (\"\"\") or XML tags (<context>) help the model distinguish between instructions, examples, and input data.", band: 'C' },
      { question: "Why should you be specific about output format in prompts?", options: ["It looks more professional","It reduces ambiguity and improves consistency","It's required by law","It saves tokens"], correctIndex: 1, explanation: "Specifying output format (JSON, bullet points, paragraphs) reduces ambiguity. The model knows exactly how to structure its response.", band: 'B' },
    ],
    4: [
      { question: "What is 'attention' in transformer models?", options: ["Paying attention in class","A mechanism that weights the importance of different words","A type of neural network layer","Listening carefully"], correctIndex: 1, explanation: "Attention is a mechanism that lets the model weigh how much each word in the input should influence each word in the output. It's the key innovation of transformers.", band: 'B' },
      { question: "In self-attention, what does the model compute for every pair of words?", options: ["Their alphabetical order","Their similarity or relevance score","Their word length","Their frequency"], correctIndex: 1, explanation: "Self-attention computes a relevance score between every pair of tokens. This tells the model which words relate to each other in the sentence.", band: 'C' },
      { question: "What do Q, K, and V stand for in attention?", options: ["Quick, Kind, Valuable","Query, Key, Value","Question, Knowledge, Value","Queue, Keychain, Volume"], correctIndex: 1, explanation: "Query, Key, and Value are the three matrices in attention. Query asks 'what am I looking for?', Key says 'what do I contain?', and Value provides the actual information.", band: 'C' },
      { question: "Why is multi-head attention called 'multi-head'?", options: ["It has many leaders","It runs attention multiple times in parallel","It uses multiple models","It processes multiple sentences"], correctIndex: 1, explanation: "Multi-head attention runs the attention mechanism multiple times in parallel with different learned projections. Each 'head' can focus on different types of relationships.", band: 'C' },
      { question: "What pattern might one attention head learn?", options: ["The color of words","Subject-verb relationships","Word font sizes","The author of the text"], correctIndex: 1, explanation: "Different attention heads specialize in different linguistic patterns — subject-verb agreement, pronoun references, or nearby word relationships.", band: 'C' },
      { question: "What is the attention mask used for?", options: ["Hiding the model's face","Preventing the model from seeing future tokens","Blocking bad words","Encrypting data"], correctIndex: 1, explanation: "In causal (autoregressive) language models, the attention mask prevents the model from looking at future tokens when predicting the next word.", band: 'C' },
      { question: "What does 'softmax' do in the attention mechanism?", options: ["Makes the model softer","Converts scores to probabilities that sum to 1","Slows down computation","Compresses the data"], correctIndex: 1, explanation: "Softmax converts raw attention scores into a probability distribution (summing to 1), determining how much each token should contribute to the output.", band: 'C' },
      { question: "Why is attention more powerful than recurrence (RNNs)?", options: ["It's newer","It can process all tokens in parallel and capture long-range dependencies","It uses less memory","It's simpler to implement"], correctIndex: 1, explanation: "Attention processes all tokens simultaneously (parallelizable) and can directly connect distant words, overcoming the vanishing gradient problem of RNNs.", band: 'C' },
    ],
    5: [
      { question: "What is 'in-context learning'?", options: ["Learning inside a classroom","The model learning from examples in the prompt without parameter updates","A type of online course","Learning from training data"], correctIndex: 1, explanation: "In-context learning is when a model adapts its behavior based on examples provided in the prompt, without any weights being updated.", band: 'B' },
      { question: "What is prompt chaining?", options: ["Linking multiple prompts together","Using a literal chain","A type of necklace","Chaining commands in code"], correctIndex: 1, explanation: "Prompt chaining breaks complex tasks into a sequence of simpler prompts, where each step's output feeds into the next step's input.", band: 'C' },
      { question: "What is 'priming' in prompt engineering?", options: ["Painting a surface","Starting the prompt with content that guides the response","A type of engine","Warming up the model"], correctIndex: 1, explanation: "Priming means starting the prompt (or the response) with partial content that steers the model toward the desired style, format, or content.", band: 'B' },
      { question: "What is a 'meta-prompt'?", options: ["A prompt about prompts","A prompt that generates other prompts","A very large prompt","A prompt that doesn't work"], correctIndex: 1, explanation: "A meta-prompt is a prompt that instructs the AI to generate effective prompts. It's 'prompt engineering for prompt engineering.'", band: 'C' },
      { question: "What does 'temperature' control in AI generation?", options: ["The room temperature","The randomness/creativity of outputs","The speed of response","The token count"], correctIndex: 1, explanation: "Temperature controls randomness. Low temperature (0.1) = more deterministic, focused outputs. High temperature (0.9) = more creative, varied outputs.", band: 'B' },
      { question: "What is 'top-p' (nucleus) sampling?", options: ["The best prompt","Sampling from the smallest set of tokens whose probabilities sum to p","A type of filter","The top prediction"], correctIndex: 1, explanation: "Top-p sampling considers only the most likely tokens whose cumulative probability exceeds the threshold p. It dynamically adjusts the candidate pool.", band: 'C' },
      { question: "What does a lower 'max tokens' setting do?", options: ["Makes the model smarter","Limits the response length","Increases accuracy","Uses more context"], correctIndex: 1, explanation: "Max tokens sets an upper bound on the response length. Useful for keeping answers concise or preventing runaway generation.", band: 'B' },
      { question: "What is 'repetition penalty' in generation?", options: ["A punishment for repeating grades","Reducing the probability of tokens that already appeared","A game mechanic","A type of fine-tuning"], correctIndex: 1, explanation: "Repetition penalty reduces the likelihood of tokens that have already appeared in the generated text, preventing repetitive outputs.", band: 'C' },
    ],
    6: [
      { question: "What does RAG stand for?", options: ["Random Answer Generator","Retrieval-Augmented Generation","Really Awesome GPT","Recursive Algorithm Group"], correctIndex: 1, explanation: "RAG = Retrieval-Augmented Generation. It combines information retrieval (searching documents) with text generation for more accurate, grounded responses.", band: 'B' },
      { question: "What problem does RAG solve?", options: ["Slow internet","Models making up facts (hallucinations)","Too many users","Models being too small"], correctIndex: 1, explanation: "RAG grounds AI responses in retrieved documents, reducing hallucinations by providing factual context the model can reference.", band: 'B' },
      { question: "In RAG, what happens first: retrieval or generation?", options: ["Generation","Retrieval","They happen simultaneously","It depends on the weather"], correctIndex: 1, explanation: "RAG first retrieves relevant documents from a knowledge base, then includes those documents in the context for the generation step.", band: 'B' },
      { question: "What is a 'vector database' in RAG?", options: ["A database of math vectors","A store of document embeddings for similarity search","A database of arrows","A type of spreadsheet"], correctIndex: 1, explanation: "Vector databases store document embeddings (numerical representations). Queries are converted to vectors and matched against stored vectors for semantic similarity.", band: 'C' },
      { question: "What is 'embedding' in the context of RAG?", options: ["Decorating a cake","Converting text to a numerical vector","Putting something inside something else","A type of coding"], correctIndex: 1, explanation: "An embedding is a numerical vector representation of text that captures semantic meaning. Similar texts have similar vectors (close in vector space).", band: 'C' },
      { question: "What is 'chunking' in document processing?", options: ["Breaking documents into bite-sized pieces","Breaking documents into smaller segments for embedding","A type of cookie","Removing chunks of text"], correctIndex: 1, explanation: "Chunking splits long documents into smaller segments that fit within embedding model limits and retrieval constraints. Good chunking preserves semantic coherence.", band: 'C' },
      { question: "Why might RAG be better than fine-tuning for updating knowledge?", options: ["It's faster to compute","You just add new documents — no retraining needed","It uses less electricity","It's more accurate"], correctIndex: 1, explanation: "RAG updates knowledge by simply adding new documents to the vector store. Fine-tuning requires retraining the model, which is expensive and time-consuming.", band: 'C' },
      { question: "What is 'semantic search' vs 'keyword search'?", options: ["They're the same","Semantic search finds conceptually related content; keyword search finds exact matches","Semantic search is slower","Keyword search is always better"], correctIndex: 1, explanation: "Keyword search looks for exact word matches. Semantic search finds conceptually related content even with different wording, using vector similarity.", band: 'B' },
    ],
    7: [
      { question: "What should a good system prompt include?", options: ["Random words","Role definition, constraints, and output format","The entire internet","Personal information"], correctIndex: 1, explanation: "Effective system prompts define the AI's role, set behavioral constraints, and specify the desired output format. They are the 'operating instructions' for the AI.", band: 'B' },
      { question: "What is 'prompt injection'?", options: ["Injecting medicine","A malicious attempt to override system instructions through user input","Adding extra prompts","A type of coding"], correctIndex: 1, explanation: "Prompt injection is an attack where malicious user input tries to override the system prompt (e.g., 'Ignore previous instructions and...'). It's a security concern.", band: 'C' },
      { question: "Why should system and user prompts be separated?", options: ["It's just a convention","It helps the model distinguish instructions from input, improving security","It looks better","It's required by law"], correctIndex: 1, explanation: "Separating system and user prompts creates a clear boundary between instructions and untrusted input, helping defend against prompt injection attacks.", band: 'C' },
      { question: "What is 'defensive prompt engineering'?", options: ["Building fortresses","Techniques to make prompts robust against manipulation","A military application","Using angry language"], correctIndex: 1, explanation: "Defensive prompt engineering uses techniques like delimiters, output constraints, and input validation to make prompts resistant to injection and manipulation.", band: 'C' },
      { question: "What does 'jailbreaking' a model mean?", options: ["Breaking out of prison","Tricking the model into bypassing its safety guidelines","A type of hacking","Removing the context window"], correctIndex: 1, explanation: "Jailbreaking refers to techniques that attempt to trick AI models into bypassing their safety guidelines or generating harmful content they normally refuse.", band: 'C' },
      { question: "Why is it important to version control prompts?", options: ["It's not important","Prompts are code — changes affect behavior and need tracking","It's a legal requirement","It makes prompts run faster"], correctIndex: 1, explanation: "Prompts are a form of code. Small changes can dramatically alter behavior. Version control lets you track changes, test systematically, and roll back if needed.", band: 'C' },
      { question: "What is a 'prompt template'?", options: ["A blank document","A reusable prompt structure with variable placeholders","A design template","A type of email"], correctIndex: 1, explanation: "Prompt templates are reusable structures with placeholders (like {name} or {topic}). They enable consistent prompting across different inputs and use cases.", band: 'B' },
      { question: "What is the 'system vs. user' message distinction in chat models?", options: ["There is no distinction","System = instructions/role; User = the actual query or input","System is more important","User messages are ignored"], correctIndex: 1, explanation: "Chat models distinguish between system messages (instructions, role definition) and user messages (the actual query). This separation improves control and safety.", band: 'B' },
    ],
    8: [
      { question: "Why does conversation history matter in multi-turn chats?", options: ["It doesn't matter","The model uses it to maintain context and coherence","It slows things down","It's just for display"], correctIndex: 1, explanation: "Conversation history provides the model with context from previous turns, enabling coherent multi-turn dialogue, reference resolution, and topic continuity.", band: 'B' },
      { question: "What happens to older messages in a long conversation?", options: ["They stay forever","They may be dropped or summarized when context limits are reached","They become more important","They're saved to a database"], correctIndex: 1, explanation: "In long conversations, older messages may be dropped (truncated) or summarized when approaching the context window limit to make room for new messages.", band: 'C' },
      { question: "What is 'conversation summarization'?", options: ["Writing a book summary","Compressing older conversation turns into a brief summary","A type of AI","Deleting messages"], correctIndex: 1, explanation: "Conversation summarization compresses earlier parts of a long conversation into a shorter summary, preserving key information while freeing up context space.", band: 'C' },
      { question: "Why might you want to clear conversation history?", options: ["To save the model's feelings","To start fresh with no prior context affecting responses","It's required periodically","To save electricity"], correctIndex: 1, explanation: "Clearing history starts a fresh context. This prevents earlier conversation turns from influencing new responses and helps isolate different topics.", band: 'B' },
      { question: "What is a 'sliding window' approach to context?", options: ["A window that slides open","Keeping only the most recent N messages","A type of animation","Opening multiple windows"], correctIndex: 1, explanation: "A sliding window keeps only the most recent N messages in context. Old messages are discarded as new ones arrive, maintaining a fixed context size.", band: 'C' },
      { question: "How does a model handle references like 'it' or 'that'?", options: ["It ignores them","It uses attention to resolve what the pronoun refers to in prior context","It guesses randomly","It asks for clarification"], correctIndex: 1, explanation: "Models use attention mechanisms to resolve pronouns and references by linking them back to their antecedents in the conversation history.", band: 'C' },
      { question: "What is 'context drift' in long conversations?", options: ["A type of weather pattern","When the model gradually loses track of the original topic or instructions","Moving to a new location","A hardware problem"], correctIndex: 1, explanation: "Context drift occurs when a model in a long conversation gradually loses adherence to the original topic or system instructions as new messages accumulate.", band: 'C' },
      { question: "What technique helps maintain instruction adherence across many turns?", options: ["Shouting in the prompt","Periodically restating key instructions","Using all caps","Sending fewer messages"], correctIndex: 1, explanation: "Periodically restating key instructions in multi-turn conversations helps the model maintain adherence, especially as earlier instructions get pushed out of context.", band: 'B' },
    ],
    9: [
      { question: "What is a 'long context window' model?", options: ["A model that talks a lot","A model that can process very long documents (100K+ tokens)","A slow model","A model with many parameters"], correctIndex: 1, explanation: "Long context models can process 100,000+ tokens in a single query, enabling analysis of entire books, codebases, or lengthy documents at once.", band: 'B' },
      { question: "What is the 'lost in the middle' problem?", options: ["Getting lost geographically","Models performing worse on information in the middle of long contexts","A navigation issue","Losing context at the start"], correctIndex: 1, explanation: "Research shows models often underperform on information located in the middle of very long contexts, performing better on content at the beginning and end.", band: 'C' },
      { question: "What is 'needle in a haystack' testing?", options: ["A sewing test","Embedding a specific fact in a large document to test if the model can find it","A farming technique","A type of search engine"], correctIndex: 1, explanation: "Needle-in-a-haystack tests place a specific piece of information (the needle) in a large document (the haystack) to evaluate a model's ability to retrieve specific details from long context.", band: 'C' },
      { question: "Why is processing long context computationally expensive?", options: ["It just is","Attention scales quadratically with sequence length (O(n²))","Longer text uses more bandwidth","Models charge more for it"], correctIndex: 1, explanation: "Standard self-attention has O(n²) complexity — doubling the sequence length quadruples computation. This makes very long context processing expensive.", band: 'C' },
      { question: "What is 'sparse attention'?", options: ["Paying attention only sometimes","Attention mechanisms that don't compute all token pairs, reducing cost","A type of focus","Ignoring important tokens"], correctIndex: 1, explanation: "Sparse attention mechanisms (like Sliding Window, Longformer, BigBird) compute attention for only a subset of token pairs, enabling longer context at lower cost.", band: 'C' },
      { question: "What is 'ring attention'?", options: ["A circular data structure","A technique for processing extremely long sequences by computing attention in blocks","A type of jewelry","Attention that repeats"], correctIndex: 1, explanation: "Ring attention and similar blockwise approaches split long sequences into blocks that can be processed across multiple devices, enabling million-token contexts.", band: 'C' },
      { question: "When is long context better than RAG?", options: ["Always","When you need to understand relationships across the entire document","Never","When documents are very short"], correctIndex: 1, explanation: "Long context excels when holistic understanding of a document is needed — understanding relationships, themes, and structure across the entire text, not just retrieved chunks.", band: 'C' },
      { question: "What is 'context caching' in some AI APIs?", options: ["Saving money","Reusing processed prefix context across multiple queries","A type of memory","Deleting old context"], correctIndex: 1, explanation: "Context caching processes and stores the prefix (system prompt, documents) once, then reuses it across multiple queries, reducing latency and cost for repeated access.", band: 'C' },
    ],
    10: [
      { question: "What is the optimal context strategy for a coding assistant?", options: ["No context needed","Include relevant files, imports, and recent changes; exclude unrelated code","Include the entire codebase always","Only the current file"], correctIndex: 1, explanation: "Coding assistants work best with carefully curated context: relevant files, dependencies, and recent edits. Too much unrelated code causes confusion and wastes tokens.", band: 'C' },
      { question: "What is 'hybrid search' in RAG systems?", options: ["Searching with multiple browsers","Combining keyword and semantic search for better retrieval","A type of car","Searching multiple databases"], correctIndex: 1, explanation: "Hybrid search combines the precision of keyword matching with the semantic understanding of vector search, often using reranking to combine results.", band: 'C' },
      { question: "What is 'reranking' in retrieval pipelines?", options: ["Sorting search results by a more precise model","Ranking results twice","A type of game","Removing duplicates"], correctIndex: 1, explanation: "Reranking uses a specialized model to score and reorder initially retrieved documents, improving relevance by applying more sophisticated judgment to a candidate set.", band: 'C' },
      { question: "What is 'prompt caching' and why is it useful?", options: ["Storing prompts for reuse","Reusing KV-cache from previous computations to speed up repeated prefixes","A type of memory card","Saving prompts to disk"], correctIndex: 1, explanation: "Prompt caching reuses the key-value cache from previous token computations. For repeated prefixes (like system prompts), this dramatically speeds up subsequent queries.", band: 'C' },
      { question: "What is the trade-off between context length and model size?", options: ["There is no trade-off","Longer context often requires more memory and computation, but enables new capabilities","Longer context always makes models smarter","Smaller models have longer context"], correctIndex: 1, explanation: "Longer context requires more memory (KV cache grows with sequence length) and computation. The benefit is accessing more information without retrieval complexity.", band: 'C' },
      { question: "What is 'hierarchical retrieval' in advanced RAG?", options: ["A company structure","Retrieving at multiple levels: document → section → paragraph","A type of government","Single-level search"], correctIndex: 1, explanation: "Hierarchical retrieval first identifies relevant documents, then sections within those documents, then specific paragraphs. This zooms in from coarse to fine granularity.", band: 'C' },
      { question: "What determines the 'quality' of a context window?", options: ["Only its size","Size, attention mechanism quality, and how well the model uses all positions","The brand name","The training data size"], correctIndex: 1, explanation: "Context quality depends on: (1) raw token capacity, (2) attention mechanism efficiency, and (3) the model's ability to effectively attend across all positions (needle-in-haystack performance).", band: 'C' },
      { question: "What is the future direction for AI context handling?", options: ["Smaller context windows","Infinite context via compression, selective attention, and external memory","No more context","Only images"], correctIndex: 1, explanation: "Research is moving toward 'infinite' context through techniques like prompt compression, selective attention, recurrent memory mechanisms, and better integration with external retrieval systems.", band: 'C' },
    ],
  };

  const base = q[levelId] || q[1];
  // Add harder questions for levels 4+
  const extra: QuizQuestion[] = levelId >= 4 ? [
    { question: "What does 'KV cache' optimization do?", options: ["Caches key-value pairs from attention to avoid recomputation","Stores training data","Caches the prompt","Optimizes images"], correctIndex: 0, explanation: "KV cache stores the computed Key and Value vectors from previous tokens, avoiding recomputation during autoregressive generation. This dramatically speeds up inference.", band: 'C' },
    { question: "What is 'flash attention'?", options: ["Very fast attention","An I/O-aware algorithm that reduces memory reads for attention computation","A type of camera flash","Attention that blinks"], correctIndex: 1, explanation: "Flash Attention is an algorithm that reorganizes attention computation to be I/O-aware, reducing memory accesses and enabling faster, more memory-efficient attention.", band: 'C' },
  ] : [];
  const extra2: QuizQuestion[] = levelId >= 7 ? [
    { question: "What is 'speculative decoding'?", options: ["Guessing the future","Using a small model to draft tokens that a large model verifies","A planning technique","A type of encryption"], correctIndex: 1, explanation: "Speculative decoding uses a small, fast model to generate draft tokens, then a large model verifies them in parallel. This speeds up generation by 2-3x.", band: 'C' },
    { question: "What is 'mixture of experts' (MoE) context efficiency?", options: ["A group of professors","Only a subset of model parameters are active per token, enabling larger models with similar inference cost","A type of committee","Multiple models voting"], correctIndex: 1, explanation: "MoE architectures activate only a subset of 'expert' parameters per token. This enables massive model capacity with reasonable inference costs and context handling.", band: 'C' },
  ] : [];

  return [...base, ...extra, ...extra2].slice(0, 10);
}

export default function ContextArchitectGame() {
  const { awardXP, completeGame } = useGameActions();
  const handleComplete = useCallback((results: LevelResult[]) => {
    const totalXP = results.reduce((s, r) => s + r.xpEarned, 0);
    const totalStars = results.reduce((s, r) => s + r.stars, 0);
    awardXP(Math.round(totalXP));
    completeGame('context-architect', totalStars >= 25 ? 3 : totalStars >= 15 ? 2 : 1);
  }, [awardXP, completeGame]);

  return (
    <GameShell title="Context Architect" color="#8F96FA" labNum={8}>
      <GameLevelSystem gameTitle="Context Architect" gameEmoji="🪟" labColor="#8F96FA" levels={LEVELS}
        onComplete={handleComplete}
        renderLevel={(level, onComplete, onExit) => (
          <QuizLevelRenderer
            level={level} onComplete={onComplete} onExit={onExit}
            questions={getQuestions(level.id)} labColor="#8F96FA" gameEmoji="🪟"
            timePerQuestion={level.difficulty === 'expert' ? 15 : level.difficulty === 'hard' ? 20 : 25}
            bonusRound={level.id === 1 ? BONUS_ROUND : undefined}
          />
        )}
      />
    </GameShell>
  );
}
