// SparkForge Game Registry — All 42 games
// Source of truth for game metadata, routing, and 3D budget allocation

export type GameTier = 'flagship' | 'fl-lite' | 'standard';
export type AgeBand = 'A' | 'B' | 'C';

/** Per-game camera preset for CameraSystem (Section 4.1-B) */
export interface GameCameraPreset {
  position: [number, number, number];
  lookAt: [number, number, number];
  fov: number;
}

export interface GameRegistryEntry {
  id: number;
  name: string;
  slug: string;
  lab: number;
  labName: string;
  tier: GameTier;
  has3D: boolean;
  component3D: string | null;
  ageBands: AgeBand[];
  stage: string;
  description: string;
  icon: string;
  triangleBudget: { desktop: number } | null;
  /** Per-game camera override (Section 4.1-B). Falls back to GAME_CAMERA_DEFAULT. */
  cameraPreset: GameCameraPreset | null;
}

import { LAB_NAMES } from '@/config/labs';

// ── Per-Game Camera Presets (Section 4.1-B) ──
// Games without a preset use GAME_CAMERA_DEFAULT via CameraSystem.
// Presets are designed for each game's 3D scene layout.

export const GAME_CAMERA_DEFAULT: GameCameraPreset = {
  position: [0, 2, 5],
  lookAt: [0, 0, 0],
  fov: 45,
};

const CAMERA_PRESETS: Record<string, GameCameraPreset> = {
  // Flagship — wide FOV for immersive 3D scenes
  'pet-trainer':      { position: [0, 3, 6],    lookAt: [0, 0.5, 0], fov: 50 },
  'sort-toy-box':     { position: [0, 4, 7],    lookAt: [0, 0, 0],   fov: 55 },
  'neural-builder':   { position: [0, 2.5, 5],  lookAt: [0, 1, 0],   fov: 48 },
  'prompt-lab':       { position: [0, 1.5, 4],  lookAt: [0, 0.5, 0], fov: 42 },
  'agent-architect':  { position: [2, 3, 6],    lookAt: [0, 0, 0],   fov: 52 },
  'bias-detective':   { position: [0, 2, 5.5],  lookAt: [0, 0.8, 0], fov: 46 },
  // FL-Lite — moderate depth, focused view
  'data-detective':   { position: [0, 2, 4.5],  lookAt: [0, 0, 0],   fov: 44 },
  'robot-vacuum':     { position: [0, 5, 8],    lookAt: [0, 0, 0],   fov: 55 },
  'camera-quest':     { position: [0, 1.5, 4],  lookAt: [0, 0, 0],   fov: 50 },
  'chatbot-builder':  { position: [0, 2, 4],    lookAt: [0, 0.5, 0], fov: 43 },
  'emoji-decoder':    { position: [0, 1.5, 3.5],lookAt: [0, 0, 0],   fov: 40 },
  'code-blocks':      { position: [0, 3, 5],    lookAt: [0, 0, 0],   fov: 48 },
  'my-first-ai-app':  { position: [0, 2, 4],    lookAt: [0, 0, 0],   fov: 44 },
  'future-forge':     { position: [0, 2.5, 5.5],lookAt: [0, 0, 0],   fov: 50 },
  'ai-or-not':        { position: [0, 1.5, 4],  lookAt: [0, 0, 0],   fov: 42 },
  // Lab 11 (April 30, 2026): Agentic AI flagship cohort
  'agent-atelier':    { position: [0, 4, 8],    lookAt: [0, 0, 0],   fov: 55 },
  'mcp-lab':          { position: [0, 4, 8.5],  lookAt: [0, 0, 0],   fov: 55 },
  'glass-box':        { position: [0, 3.5, 7],  lookAt: [0, 1, 0],   fov: 50 },
  'harness-forge':    { position: [0, 3.5, 8],  lookAt: [0, 0.5, 0], fov: 52 },
  // Lab 1 (May 1, 2026): C5 Pocket Brain - tabletop close-up framing
  // matches Doc 2 §H.8 camera preset
  'pocket-brain':     { position: [0, 1.5, 4],  lookAt: [0, 0.8, 0], fov: 42 },
  // Lab 8 (May 1, 2026): C2 Context Architect - library reading-lectern
  // framing matches Doc 2 §E.8
  'context-architect': { position: [0, 2, 5],   lookAt: [0, 1, 0],   fov: 46 },
  // Lab 7 (May 1, 2026): C4 Pixel Witness - cinema/edit-bay framing
  // matches Doc 2 §G.8
  'pixel-witness':    { position: [0, 1.8, 4],  lookAt: [0, 0.5, 0], fov: 44 },
};

function cameraPreset(slug: string): GameCameraPreset | null {
  return CAMERA_PRESETS[slug] ?? null;
}

const TRIANGLE_BUDGETS = {
  flagship: { desktop: 20_000_000 },
  'fl-lite': { desktop: 10_000_000 },
  standard3D: { desktop: 5_000_000 },
} as const;

function budget(tier: GameTier, has3D: boolean) {
  if (!has3D) return null;
  if (tier === 'flagship') return { ...TRIANGLE_BUDGETS.flagship };
  if (tier === 'fl-lite') return { ...TRIANGLE_BUDGETS['fl-lite'] };
  return { ...TRIANGLE_BUDGETS.standard3D };
}

export const GAME_REGISTRY: readonly GameRegistryEntry[] = [
  {
    id: 1,
    name: 'AI Spy',
    slug: 'ai-spy',
    lab: 1,
    labName: LAB_NAMES[1],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7A',
    description: 'Spot hidden AI systems in everyday scenes by tapping on objects that use artificial intelligence.',
    icon: '\uD83D\uDD75\uFE0F',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 2,
    name: 'Time Machine',
    slug: 'time-machine',
    lab: 1,
    labName: LAB_NAMES[1],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7A',
    description: 'Travel through the history of AI and place key milestones on a timeline.',
    icon: '\u23F3',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 3,
    name: 'Human vs Machine',
    slug: 'human-vs-machine',
    lab: 1,
    labName: LAB_NAMES[1],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7B',
    description: 'Drag tasks into human or machine categories to learn what AI does best versus what humans excel at.',
    icon: '\uD83E\uDD1D',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 4,
    name: 'AI Pet Trainer',
    slug: 'pet-trainer',
    lab: 2,
    labName: LAB_NAMES[2],
    tier: 'flagship',
    has3D: true,
    component3D: 'Pet3DScene',
    ageBands: ['A', 'B', 'C'],
    stage: '6B',
    description: 'Explore how an AI pet learns — adjust its training settings and see how your choices shape the way it behaves.',
    icon: '\uD83D\uDC3E',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('pet-trainer'),
  },
  {
    id: 5,
    name: 'Sort Toy Box',
    slug: 'sort-toy-box',
    lab: 2,
    labName: LAB_NAMES[2],
    tier: 'flagship',
    has3D: true,
    component3D: 'SortScene3D',
    ageBands: ['A', 'B', 'C'],
    stage: '7B',
    description: 'Toss toys into the correct bins to learn how AI classifies and sorts objects into categories.',
    icon: '\uD83E\uDDF8',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('sort-toy-box'),
  },
  {
    id: 6,
    name: 'Treat Trainer',
    slug: 'treat-trainer',
    lab: 2,
    labName: LAB_NAMES[2],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7C',
    description: 'Reward or correct an AI dog to teach it tricks, exploring how positive reinforcement shapes behavior.',
    icon: '\uD83C\uDF56',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 7,
    name: 'Data Detective',
    slug: 'data-detective',
    lab: 2,
    labName: LAB_NAMES[2],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'DataDetective3D',
    ageBands: ['A', 'B', 'C'],
    stage: '7C',
    description: 'Investigate datasets with a magnifying glass to find patterns, outliers, and hidden insights.',
    icon: '\uD83D\uDD0D',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('data-detective'),
  },
  {
    id: 8,
    name: 'Neural Builder',
    slug: 'neural-builder',
    lab: 3,
    labName: LAB_NAMES[3],
    tier: 'flagship',
    has3D: true,
    component3D: 'NeuralNetwork3D',
    ageBands: ['B', 'C'],
    stage: '6C',
    description: 'Construct a neural network by connecting neurons and layers, then watch data flow through your creation.',
    icon: '\uD83E\uDDE0',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('neural-builder'),
  },
  {
    id: 9,
    name: 'Neuron Relay',
    slug: 'neuron-relay',
    lab: 3,
    labName: LAB_NAMES[3],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7C',
    description: 'Pass signals through a chain of neurons to see how information travels in a neural network.',
    icon: '\u26A1',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 10,
    name: 'Pixel Investigator',
    slug: 'pixel-investigator',
    lab: 3,
    labName: LAB_NAMES[3],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7D',
    description: 'Zoom into images pixel by pixel to understand how computer vision breaks down visual information.',
    icon: '\uD83D\uDDA5\uFE0F',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 11,
    name: 'Prompt Lab',
    slug: 'prompt-lab',
    lab: 4,
    labName: LAB_NAMES[4],
    tier: 'flagship',
    has3D: true,
    component3D: 'PromptBubble3D',
    ageBands: ['A', 'B', 'C'],
    stage: '6D',
    description: 'Craft and refine prompts to communicate with an AI, learning how word choice shapes responses.',
    icon: '\uD83D\uDCAC',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('prompt-lab'),
  },
  {
    id: 12,
    name: 'Word Predictor',
    slug: 'word-predictor',
    lab: 4,
    labName: LAB_NAMES[4],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7A',
    description: 'Guess the next word in a sentence to discover how language models predict text.',
    icon: '\uD83D\uDD24',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 13,
    name: 'Token Chopper',
    slug: 'token-chopper',
    lab: 4,
    labName: LAB_NAMES[4],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['B', 'C'],
    stage: '7A',
    description: 'Slice sentences into tokens to learn how AI breaks language into smaller pieces for processing.',
    icon: '\u2702\uFE0F',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 14,
    name: 'AI Art Detective',
    slug: 'ai-art-detective',
    lab: 4,
    labName: LAB_NAMES[4],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7A',
    description: 'Examine artwork to determine whether it was created by a human artist or generated by AI.',
    icon: '\uD83C\uDFA8',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 15,
    name: 'Agent Architect',
    slug: 'agent-architect',
    lab: 5,
    labName: LAB_NAMES[5],
    tier: 'flagship',
    has3D: true,
    component3D: 'AgentPipeline3D',
    ageBands: ['B', 'C'],
    stage: '6E',
    description: 'Design an AI agent pipeline by connecting perception, reasoning, and action modules together.',
    icon: '\uD83E\uDDD1\u200D\uD83D\uDD27',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('agent-architect'),
  },
  {
    id: 16,
    name: 'Robot Vacuum',
    slug: 'robot-vacuum',
    lab: 5,
    labName: LAB_NAMES[5],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'RobotVacuum3D',
    ageBands: ['A', 'B', 'C'],
    stage: '7D',
    description: 'Explore how a robot vacuum decides where to go — tune its settings and see the trade-offs behind smart cleaning.',
    icon: '\uD83E\uDD16',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('robot-vacuum'),
  },
  {
    id: 17,
    name: 'Tool Picker',
    slug: 'tool-picker',
    lab: 5,
    labName: LAB_NAMES[5],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7A',
    description: 'Match real-world problems to the right AI tools to learn when and how to apply different technologies.',
    icon: '\uD83E\uDDF0',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 18,
    name: 'Bias Detective',
    slug: 'bias-detective',
    lab: 6,
    labName: LAB_NAMES[6],
    tier: 'flagship',
    has3D: true,
    component3D: 'BiasScales3D',
    ageBands: ['B', 'C'],
    stage: '6F',
    description: 'Investigate AI systems for hidden biases using scales of justice to weigh fairness in decisions.',
    icon: '\u2696\uFE0F',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('bias-detective'),
  },
  {
    id: 19,
    name: 'Data Shield',
    slug: 'data-shield',
    lab: 6,
    labName: LAB_NAMES[6],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7A',
    description: 'Protect personal data from AI collection by identifying what information should stay private.',
    icon: '\uD83D\uDEE1\uFE0F',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 20,
    name: 'Real or Fake',
    slug: 'real-or-fake',
    lab: 6,
    labName: LAB_NAMES[6],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7A',
    description: 'Analyze media to distinguish real content from AI-generated deepfakes and synthetic media.',
    icon: '\uD83E\uDD14',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 21,
    name: 'Ethics Courtroom',
    slug: 'ethics-courtroom',
    lab: 6,
    labName: LAB_NAMES[6],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['B', 'C'],
    stage: '7E',
    description: 'Debate ethical dilemmas in AI by presenting arguments for and against tough technology decisions.',
    icon: '\uD83C\uDFDB\uFE0F',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 22,
    name: 'Camera Quest',
    slug: 'camera-quest',
    lab: 7,
    labName: LAB_NAMES[7],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'CameraQuest3D',
    ageBands: ['A', 'B', 'C'],
    stage: '7D',
    description: 'Capture polaroid snapshots of objects to train an image recognition model in a scavenger hunt.',
    icon: '\uD83D\uDCF7',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('camera-quest'),
  },
  {
    id: 23,
    name: 'Fool the AI',
    slug: 'fool-the-ai',
    lab: 7,
    labName: LAB_NAMES[7],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7D',
    description: 'Create adversarial examples that trick an AI image classifier into making wrong predictions.',
    icon: '\uD83C\uDFAD',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 24,
    name: 'Build Classifier',
    slug: 'build-classifier',
    lab: 7,
    labName: LAB_NAMES[7],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['B', 'C'],
    stage: '7E',
    description: 'Build your own image classifier by labeling training data and testing its accuracy.',
    icon: '\uD83D\uDDC2\uFE0F',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 25,
    name: 'Prediction Market',
    slug: 'prediction-market',
    lab: 7,
    labName: LAB_NAMES[7],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7A',
    description: 'Make predictions about future AI trends and compare your forecasts against crowd wisdom.',
    icon: '\uD83D\uDCC8',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 26,
    name: 'Sentiment Scanner',
    slug: 'sentiment-scanner',
    lab: 8,
    labName: LAB_NAMES[8],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7C',
    description: 'Analyze text messages to detect emotional tone and learn how AI understands human sentiment.',
    icon: '\uD83D\uDE00',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 27,
    name: 'Chatbot Builder',
    slug: 'chatbot-builder',
    lab: 8,
    labName: LAB_NAMES[8],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'ChatbotNodes3D',
    ageBands: ['B', 'C'],
    stage: '7C',
    description: 'Design a chatbot conversation flow by connecting dialogue nodes and response branches.',
    icon: '\uD83D\uDCAC',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('chatbot-builder'),
  },
  {
    id: 28,
    name: 'Lost in Translation',
    slug: 'lost-in-translation',
    lab: 8,
    labName: LAB_NAMES[8],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: '7C',
    description: 'Translate phrases through multiple languages to see how meaning shifts in AI translation.',
    icon: '\uD83C\uDF10',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 29,
    name: 'Emoji Decoder',
    slug: 'emoji-decoder',
    lab: 8,
    labName: LAB_NAMES[8],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'EmojiDecoder3D',
    ageBands: ['A', 'B'],
    stage: '7F',
    description: 'Decode emoji sequences into sentences to explore how AI interprets visual symbols as language.',
    icon: '\uD83D\uDD23',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('emoji-decoder'),
  },
  {
    id: 30,
    name: 'Code Blocks',
    slug: 'code-blocks',
    lab: 9,
    labName: LAB_NAMES[9],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'CodeBlocks3D',
    ageBands: ['A', 'B', 'C'],
    stage: '7B',
    description: 'Snap together code blocks to build simple AI programs and see them execute in real time.',
    icon: '\uD83E\uDDE9',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('code-blocks'),
  },
  {
    id: 31,
    name: 'Career Explorer',
    slug: 'career-explorer',
    lab: 9,
    labName: LAB_NAMES[9],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['B', 'C'],
    stage: '7B',
    description: 'Explore AI-related careers by matching skills and interests to jobs in the AI industry.',
    icon: '\uD83D\uDCBC',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 32,
    name: 'API Explorer',
    slug: 'api-explorer',
    lab: 9,
    labName: LAB_NAMES[9],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['C'],
    stage: '7E',
    description: 'Send requests to real AI APIs and inspect responses to learn how software talks to AI services.',
    icon: '\uD83D\uDD0C',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 33,
    name: 'My First AI App',
    slug: 'my-first-ai-app',
    lab: 9,
    labName: LAB_NAMES[9],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'MyFirstAiApp3D',
    ageBands: ['A', 'B', 'C'],
    stage: '7F',
    description: 'Build a simple AI-powered app from scratch using a visual mockup builder with drag-and-drop components.',
    icon: '\uD83D\uDCF1',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('my-first-ai-app'),
  },
  {
    id: 34,
    name: 'Future Forge',
    slug: 'future-forge',
    lab: 10,
    labName: LAB_NAMES[10],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'FutureForge3D',
    ageBands: ['A', 'B', 'C'],
    stage: '7D',
    description: 'Design blueprints for future AI inventions and simulate their impact on society.',
    icon: '\uD83D\uDD2E',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('future-forge'),
  },
  {
    id: 35,
    name: 'AI or Not?',
    slug: 'ai-or-not',
    lab: 10,
    labName: LAB_NAMES[10],
    tier: 'fl-lite',
    has3D: true,
    component3D: 'AiOrNot3D',
    ageBands: ['A', 'B'],
    stage: '7F',
    description: 'Judge whether creative works were made by humans or AI to sharpen your detection skills.',
    icon: '\u2753',
    triangleBudget: budget('fl-lite', true),
    cameraPreset: cameraPreset('ai-or-not'),
  },
  // \u2500\u2500 Lab 11 (Agentic AI) \u2014 Stage 11D first flagship (April 30, 2026)
  // Build \u2192 Equip \u2192 Constrain narrative arc, Stage 1: Build.
  {
    id: 36,
    name: 'Agent Atelier',
    slug: 'agent-atelier',
    lab: 11,
    labName: LAB_NAMES[11],
    tier: 'flagship',
    has3D: true,
    component3D: 'AgentAtelier3D',
    ageBands: ['A', 'B', 'C'],
    stage: '11D',
    description: 'Explore how a team of AI agents is set up to hand work from one specialist to the next.',
    icon: '\ud83c\udfad',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('agent-atelier'),
  },
  // \u2500\u2500 Lab 11 \u2014 Stage 11E (May 1, 2026): Equip step
  {
    id: 37,
    name: 'MCP Plug-and-Play Lab',
    slug: 'mcp-lab',
    lab: 11,
    labName: LAB_NAMES[11],
    tier: 'flagship',
    has3D: true,
    component3D: 'McpLab3D',
    ageBands: ['A', 'B', 'C'],
    stage: '11E',
    description: 'Discover how giving an AI agent new tools expands what it is able to do.',
    icon: '\ud83d\udd0c',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('mcp-lab'),
  },
  // \u2500\u2500 Lab 11 \u2014 Stage 11F (May 1, 2026): Audit step
  {
    id: 38,
    name: 'Glass Box Lab',
    slug: 'glass-box',
    lab: 11,
    labName: LAB_NAMES[11],
    tier: 'flagship',
    has3D: true,
    component3D: 'GlassBox3D',
    ageBands: ['A', 'B', 'C'],
    stage: '11F',
    description: 'Learn to look inside an AI agent and follow its step-by-step reasoning to find where it goes wrong.',
    icon: '\ud83d\udd0d',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('glass-box'),
  },
  // \u2500\u2500 Lab 11 \u2014 Stage 11G (May 1, 2026): Constrain step
  // Closes the Build \u2192 Equip \u2192 Audit \u2192 Constrain narrative arc.
  {
    id: 39,
    name: 'Harness Forge',
    slug: 'harness-forge',
    lab: 11,
    labName: LAB_NAMES[11],
    tier: 'flagship',
    has3D: true,
    component3D: 'HarnessForge3D',
    ageBands: ['A', 'B', 'C'],
    stage: '11G',
    description: 'Explore the three layers that keep an AI agent safe: filtering inputs, validating outputs, and monitoring behavior.',
    icon: '\ud83d\udee1\ufe0f',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('harness-forge'),
  },
  // \u2500\u2500 Lab 1 \u2014 Stage 11A (May 1, 2026): C5 Pocket Brain
  // 'There's a real AI living in this browser tab.' Headline flagship
  // for Lab 1 (What IS AI?). Runs a real LLM client-side via WebGPU.
  {
    id: 40,
    name: 'Pocket Brain',
    slug: 'pocket-brain',
    lab: 1,
    labName: LAB_NAMES[1],
    tier: 'flagship',
    has3D: true,
    component3D: 'PocketBrain3D',
    ageBands: ['A', 'B', 'C'],
    stage: '11A',
    description: 'Learn how a tiny AI model can run entirely on a device \u2014 no internet, server, or API key needed.',
    icon: '\ud83e\udde0',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('pocket-brain'),
  },
  // \u2500\u2500 Lab 8 \u2014 Stage 11B (May 1, 2026): C2 Context Architect
  // 'The AI's brain has a shelf, and the shelf is small.' Curate cards,
  // manage tokens, beat Context Rot via 4 canonical moves.
  {
    id: 41,
    name: 'Context Architect',
    slug: 'context-architect',
    lab: 8,
    labName: LAB_NAMES[8],
    tier: 'flagship',
    has3D: true,
    component3D: 'ContextShelf3D',
    ageBands: ['A', 'B', 'C'],
    stage: '11B',
    description: 'Learn how to manage an AI\'s limited memory — choose what to keep so its context stays clean.',
    icon: '\ud83d\udcda',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('context-architect'),
  },
  // \u2500\u2500 Lab 7 \u2014 Stage 11C (May 1, 2026): C4 Pixel Witness
  // 'Watch the clip. Now ask the AI what happened. Then catch the lies.'
  // Closes the canonical Stage 11A-G plan to 7/7.
  {
    id: 42,
    name: 'Pixel Witness',
    slug: 'pixel-witness',
    lab: 7,
    labName: LAB_NAMES[7],
    tier: 'flagship',
    has3D: true,
    component3D: 'PixelWitness3D',
    ageBands: ['A', 'B', 'C'],
    stage: '11C',
    description: 'Learn how an AI describes what it "sees" — and how to catch the mistakes it makes.',
    icon: '\ud83c\udfac',
    triangleBudget: budget('flagship', true),
    cameraPreset: cameraPreset('pixel-witness'),
  },
  // ── G4 (new-2026-curriculum games; ids 43–47). No 3D — bespoke DOM/SVG. ──
  {
    id: 43,
    name: 'Just a Friend?',
    slug: 'just-a-friend',
    lab: 6,
    labName: LAB_NAMES[6],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['B', 'C'],
    stage: 'G4',
    description: 'Chat with an AI companion — and learn to spot the tricks it uses to keep you hooked.',
    icon: '🫂',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 44,
    name: 'Trace It',
    slug: 'trace-it',
    lab: 10,
    labName: LAB_NAMES[10],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['B', 'C'],
    stage: 'G4',
    description: 'AI search can sound sure and still be wrong. Trace the sources, then rule: trust, fix, or flag.',
    icon: '🔎',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 45,
    name: 'Vibe Coder',
    slug: 'vibe-coder',
    lab: 9,
    labName: LAB_NAMES[9],
    tier: 'fl-lite',
    has3D: false,
    component3D: null,
    ageBands: ['B', 'C'],
    stage: 'G4',
    description: 'Describe an app, let the AI code it — then find the bug it left behind. Verifying is the real skill.',
    icon: '🎛️',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 46,
    name: 'Code Word',
    slug: 'code-word',
    lab: 6,
    labName: LAB_NAMES[6],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: 'G4',
    description: 'A voice can be faked. Learn the safe move — a family code word, a call back — before you trust it.',
    icon: '🔐',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    id: 47,
    name: 'Thinking Cap',
    slug: 'thinking-cap',
    lab: 4,
    labName: LAB_NAMES[4],
    tier: 'standard',
    has3D: false,
    component3D: null,
    ageBands: ['B', 'C'],
    stage: 'G4',
    description: 'One AI blurts, one shows its thinking. Check the steps — even shown reasoning can be wrong.',
    icon: '🧢',
    triangleBudget: null,
    cameraPreset: null,
  },
  {
    // Forge F8 (Concept 10 Part 12) — game #43. Arcade visibility is
    // gated by FEATURE_FLAGS.GAME_CORE_IGNITION (see arcade pages).
    id: 43,
    name: 'Core Ignition',
    slug: 'core-ignition',
    lab: 9,
    labName: LAB_NAMES[9],
    tier: 'flagship',
    has3D: false,
    component3D: null,
    ageBands: ['A', 'B', 'C'],
    stage: 'F8',
    description: 'Race a molten data stream and forge prompts in mid-run to break through the walls that stop weak prompts cold.',
    icon: '🔥',
    triangleBudget: null,
    cameraPreset: null,
  },
] as const;

// ---------------------------------------------------------------------------
// Helper functions
// ---------------------------------------------------------------------------

/** Find a game by its URL slug. Returns undefined if not found. */
export function getGameBySlug(slug: string): GameRegistryEntry | undefined {
  return GAME_REGISTRY.find((g) => g.slug === slug);
}

/** Get all games belonging to a specific lab (1-10). */
export function getGamesByLab(lab: number): GameRegistryEntry[] {
  return GAME_REGISTRY.filter((g) => g.lab === lab);
}

/** Get all games of a specific tier. */
export function getGamesByTier(tier: GameTier): GameRegistryEntry[] {
  return GAME_REGISTRY.filter((g) => g.tier === tier);
}

/** Get all flagship games (full 3D immersive experiences). */
export function getFlagshipGames(): GameRegistryEntry[] {
  return GAME_REGISTRY.filter((g) => g.tier === 'flagship');
}

/** Get all games available for a given age band. */
export function getGamesForAgeBand(band: AgeBand): GameRegistryEntry[] {
  return GAME_REGISTRY.filter((g) => g.ageBands.includes(band));
}

/**
 * Calculate the total triangle budget across all 3D games.
 * Useful for estimating overall GPU load if all scenes were loaded simultaneously.
 * Desktop-only (D3D-1) — no tablet/mobile columns.
 */
export function getTotalTriangleBudget(): number {
  return GAME_REGISTRY.reduce((total, game) => {
    if (!game.triangleBudget) return total;
    return total + game.triangleBudget.desktop;
  }, 0);
}
