// ════════════════════════════════════════════════════════════════
// shaderManifest — Phase 5 task #1 (§10.11) Ultra sub-module
// Worker-side shader precompile manifest
// ════════════════════════════════════════════════════════════════
// Problem: three.js r183 compiles GLSL shaders the first time a
// material is rendered. In a worker context this means the worker
// stalls mid-frame on first paint of every new material — visible
// as "shader compilation hitches" when the user enters a new scene.
//
// Solution: a manifest of shader programs the worker should compile
// before the first visible frame. The worker calls `renderer.compile
// (scene, camera)` against a placeholder scene assembled from the
// manifest on init.
//
// The manifest is static data, generated by hand here for the scenes
// that matter most (hero, cockpit shell, spatial dashboard). It can
// be regenerated automatically by scanning the built JS bundle (see
// scripts/generate-shader-manifest.mjs — future work).
//
// Design notes (Mythos §8.11 depth-wise LoRA analogy): treat each
// scene's shader set as a shared base + per-scene delta. We precompile
// the shared base once, then lazy-compile scene deltas as scenes become
// visible. Total warm-up cost is proportional to the base size, not
// the sum of scene sizes.
// ════════════════════════════════════════════════════════════════

export type ShaderManifestEntry = {
  /** Human-readable label for telemetry / debug. */
  id: string;
  /** Group — compiled together and kept resident. */
  group: 'core' | 'hero' | 'cockpit' | 'spatial' | 'game' | 'postfx';
  /** Material class from three.js — used to instantiate a probe. */
  materialClass:
    | 'MeshStandardMaterial'
    | 'MeshPhysicalMaterial'
    | 'MeshBasicMaterial'
    | 'ShaderMaterial'
    | 'LineBasicMaterial'
    | 'PointsMaterial'
    | 'SpriteMaterial';
  /**
   * Optional feature flags passed to the material constructor so the
   * compiled program matches runtime usage (e.g. transparent + skinning
   * yields a different program than opaque + static).
   */
  features?: {
    transparent?: boolean;
    fog?: boolean;
    skinning?: boolean;
    morphTargets?: boolean;
    instanced?: boolean;
    clipping?: boolean;
  };
  /** Optional lights required for correct compilation. */
  lights?: Array<'ambient' | 'directional' | 'point' | 'spot' | 'hemisphere'>;
  /**
   * Estimated compile cost (ms) on a mid-range laptop — used by
   * auto-quality to defer expensive programs when FPS is low.
   */
  estCostMs?: number;
};

/**
 * The core manifest. Keep sorted by group then id for stable diffs.
 *
 * To regenerate automatically from the bundle, run:
 *   npm run build:shader-manifest (future script)
 */
export const SHADER_MANIFEST: ReadonlyArray<ShaderManifestEntry> = Object.freeze([
  // ── core (shared across every scene) ────────────────────────────
  {
    id: 'core.standard.opaque',
    group: 'core',
    materialClass: 'MeshStandardMaterial',
    features: { fog: true },
    lights: ['ambient', 'directional'],
    estCostMs: 8,
  },
  {
    id: 'core.standard.transparent',
    group: 'core',
    materialClass: 'MeshStandardMaterial',
    features: { transparent: true, fog: true },
    lights: ['ambient', 'directional'],
    estCostMs: 10,
  },
  {
    id: 'core.basic.sprite',
    group: 'core',
    materialClass: 'SpriteMaterial',
    features: { transparent: true },
    estCostMs: 2,
  },
  {
    id: 'core.line.basic',
    group: 'core',
    materialClass: 'LineBasicMaterial',
    features: { transparent: true, fog: true },
    estCostMs: 3,
  },
  {
    id: 'core.points.basic',
    group: 'core',
    materialClass: 'PointsMaterial',
    features: { transparent: true },
    estCostMs: 4,
  },

  // ── hero (8-phase animation intro) ──────────────────────────────
  {
    id: 'hero.physical.crystal',
    group: 'hero',
    materialClass: 'MeshPhysicalMaterial',
    features: { transparent: true, fog: true, clipping: true },
    lights: ['ambient', 'directional', 'point'],
    estCostMs: 24,
  },
  {
    id: 'hero.shader.veins',
    group: 'hero',
    materialClass: 'ShaderMaterial',
    features: { transparent: true },
    estCostMs: 18,
  },
  {
    id: 'hero.points.particles',
    group: 'hero',
    materialClass: 'PointsMaterial',
    features: { transparent: true },
    estCostMs: 5,
  },

  // ── cockpit (always-visible post-hero shell) ────────────────────
  {
    id: 'cockpit.physical.chrome',
    group: 'cockpit',
    materialClass: 'MeshPhysicalMaterial',
    features: { fog: true, clipping: true },
    lights: ['ambient', 'directional', 'point'],
    estCostMs: 22,
  },
  {
    id: 'cockpit.shader.holographic',
    group: 'cockpit',
    materialClass: 'ShaderMaterial',
    features: { transparent: true, fog: true },
    estCostMs: 14,
  },
  {
    id: 'cockpit.line.accent',
    group: 'cockpit',
    materialClass: 'LineBasicMaterial',
    features: { transparent: true },
    estCostMs: 2,
  },
  {
    id: 'cockpit.standard.panel',
    group: 'cockpit',
    materialClass: 'MeshStandardMaterial',
    features: { fog: true },
    lights: ['ambient', 'directional'],
    estCostMs: 6,
  },

  // ── spatial (holographic lab map + consoles) ────────────────────
  {
    id: 'spatial.shader.labmap',
    group: 'spatial',
    materialClass: 'ShaderMaterial',
    features: { transparent: true, fog: true },
    estCostMs: 16,
  },
  {
    id: 'spatial.physical.console',
    group: 'spatial',
    materialClass: 'MeshPhysicalMaterial',
    features: { fog: true },
    lights: ['ambient', 'directional', 'point', 'spot'],
    estCostMs: 20,
  },

  // ── postfx (eagerly loaded when D3D-5 on) ───────────────────────
  {
    id: 'postfx.shader.bloom',
    group: 'postfx',
    materialClass: 'ShaderMaterial',
    features: { transparent: true },
    estCostMs: 12,
  },
  {
    id: 'postfx.shader.chromatic',
    group: 'postfx',
    materialClass: 'ShaderMaterial',
    features: { transparent: true },
    estCostMs: 8,
  },
  {
    id: 'postfx.shader.vignette',
    group: 'postfx',
    materialClass: 'ShaderMaterial',
    features: { transparent: true },
    estCostMs: 4,
  },

  // ── game (per-game deltas; compiled lazy, entry when game boots) ─
  {
    id: 'game.shader.particles',
    group: 'game',
    materialClass: 'PointsMaterial',
    features: { transparent: true },
    estCostMs: 5,
  },
  {
    id: 'game.shader.highlight',
    group: 'game',
    materialClass: 'ShaderMaterial',
    features: { transparent: true },
    estCostMs: 8,
  },
]);

/**
 * Get all entries for a group (stable order). Used by the worker on
 * init and when a new scene becomes visible.
 */
export function getManifestGroup(
  group: ShaderManifestEntry['group'],
): ShaderManifestEntry[] {
  return SHADER_MANIFEST.filter((e) => e.group === group);
}

/** Sum estimated compile cost for a set of groups. */
export function estimateGroupCostMs(groups: ShaderManifestEntry['group'][]): number {
  return SHADER_MANIFEST.filter((e) => groups.includes(e.group)).reduce(
    (acc, e) => acc + (e.estCostMs ?? 0),
    0,
  );
}

/**
 * Build groups we want warm before the first visible frame. Tuned so
 * the sum fits inside a single animation frame budget (~16ms on a
 * mid-range laptop). Callers can override with fewer groups on low-end
 * hardware via auto-quality (`autoQuality.ts`).
 */
export const DEFAULT_WARMUP_GROUPS: ShaderManifestEntry['group'][] = ['core', 'cockpit'];

/**
 * Full preload set — used on desktop-ultra when the user explicitly
 * enables "precompile all" in Settings.
 */
export const FULL_WARMUP_GROUPS: ShaderManifestEntry['group'][] = [
  'core',
  'hero',
  'cockpit',
  'spatial',
  'postfx',
];
